### ISSUE TITLE
While opening or closing garage door, getting errors

### ISSUE THREAD

**Issue by k5map** [dre2901/node-red-contrib-myq#10]
This NR node is working great except when my door is opening, closing or partially open, it gives undefined errors.  I believe this is due to its dependency on "@hjdhjd/myq" v6.0.4.  Based on what I've learned, I believe if you change your dependency to v6.0.9 and with a minor change to one of your case statements, this node can pass the device status of "opening", "closing" or "stopped" which would eliminate the undefined errors.

**Comment by dre2901** [comment]
Fixed in 0.0.10
