### ISSUE TITLE
Newest version generating: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by rgerrans** [dre2901/node-red-contrib-myq#11]
Just updated to the newest version and getting the error ERR_REQUIRE_ESM

**Comment by dbeinke** [comment]
I am having the same issues

**Comment by k5map** [comment]
I'm using this node to monitor my garage door and gate... each time I send an INFO request, I get the current status but also get a lot of "Error received:" and "Count not refresh devices!" in the debug message area

**Comment by rgerrans** [comment]
I rolled back to the previous version and it appears to be working fine

**Comment by k5map** [comment]
I never upgraded and am running v0.0.6... @rgerrans, after downgrading are you getting any errors on INFO request?

**Comment by k5map** [comment]
Looks like the issue with the updated dependency of "@hjdhjd/myq": "7.4.2"... prior to that I believe it was 6.0.6

**Comment by dbeinke** [comment]
okay so how do I roll back?

**Comment by rgerrans** [comment]
npm install ***@***.***

**Comment by rgerrans** [comment]
I take that back. I'm getting errors with v0.0.6

**Comment by hitnrun30** [comment]
Same here, I was having issues with it working so I saw that there was an update and it made things worse

**Comment by rgerrans** [comment]
Unfortunately at this point I uninstalled it and 🤞 for an update. I can't
install 3.1 due to another node that won't work with that, so not sure if
0.0.7 will work with the new version of Node-Red w/o the error.

**Comment by dre2901** [comment]
Downgraded it to "@hjdhjd/myq": "6.0.9" but it does raises same authentication errors. The reason is the changed API endpoints which now require regional suffix '-east' or '-west' (for example, 'https://partner-identity-east.myq-cloud.com/connect/authorize' instead of simply 'https://partner-identity.myq-cloud.com/connect/authorize' as it is now). 
This change is only supported in myq > 7.1.0 but since it was also then require ES modules and node > 18, then it might not work in node-red :( . 
Will have to fork and patch the version 6..

**Comment by rgerrans** [comment]
Great, thanks. I'm running Node v18, I assume I just need to add ES through npm then?

**Comment by dre2901** [comment]
My Raspi is not on v18 and it's not easy to upgrade it unfortunately, so I will stick with an older one ;)
Just released 0.0.9 with patched version of myq and support of region on configuration screen. Per default, 'east' is selected. Works on my side without any errors in console. So fingers crossed they will not come up with some more endpoint changes

**Comment by k5map** [comment]
@dre2901 ... much thanks for getting this fixed.  Would it be possible to include the ability to report status of "opening, closing and stopped"?  I have a MyQ gate and garage door opener.  Both generate "undefined" errors when they are in those states.

**Comment by dre2901** [comment]
opening/closing errors were fixed in 0.0.10 (was a trivial bug)
