### ISSUE TITLE
Receiving errors with v0.0.15

### ISSUE THREAD

**Issue by k5map** [dre2901/node-red-contrib-myq#14]
I just upgraded to v0.0.15 and now am seeing this error:

myQ API error: Temporary myQ API server-side issues encountered: 429 - Too Many Requests.
Could not refresh devices!

I'm only doing refresh request at the rate of once every 15 seconds which hasn't been a problem for years.

Also, I don't see an option to choose West or East as I could in the previous version.

**Comment by dre2901** [comment]
I had the same. I had to wait a couple of hours without any requests and then it disappeared. Maybe the previous version was causing too many requests so you need to wait until server unlocks you again.

**Comment by k5map** [comment]
@dre2901 ... after reading your email, I checked my NR and you are right.  I'm not receiving any errors now.  Thanks again for keeping this node updated.
