### ISSUE TITLE
Where do I find serial number?

### ISSUE THREAD

**Issue by k5map** [dre2901/node-red-contrib-myq#4]
I have both a MyQ garage door opener and gate opener.  I've installed your node but one of the inputs is serial #.  Is this the serial # on each device or is this data located somewhere else?

**Comment by Horse2370** [comment]
Depends on the model but it will be on a label somewhere on the unit. For example
[https://support.chamberlaingroup.com/s/locate-model-number]

**Comment by k5map** [comment]
I'm still unable to use this node.  I confirmed my username, password and serial number is correct by installing this API [https://github.com/thomasmunduchira/myq-api](url).  I successfully ran a test js which listed all of my devices and their info.

When I use this info and attempt to get a list of devices using this node, I receive 5 error messages (Error received, MyQError: Unidentified error returned from service, Error code: ERR_MYQ_INVALID_SERVICE_RESPONSE, Error message: Unidentified error returned from service and MyQError: Unidentified error returned from service).

Any assistance in getting my error resolved would be greatly appreciated.

**Comment by k5map** [comment]
I posted the wrong repository... this is the one I am using (which supports V6) [https://github.com/koush/myq](url).

Here is the post I followed to install and test the API [https://github.com/thomasmunduchira/myq-api/issues/34#issuecomment-913185798](url)
