### ISSUE TITLE
v6 support?

### ISSUE THREAD

**Issue by k5map** [dre2901/node-red-contrib-myq#5]
Are you planning to update this node to support the new v6 API?  If so, have any estimate on when that might be?

**Comment by kskenyon** [comment]
Ditto

**Comment by kskenyon** [comment]
Have you seen this implementation?  Works in Homebridge.

https://www.npmjs.com/package/@hjdhjd/myq

**Comment by dre2901** [comment]
Published new version 0.0.6  with support for V6. Some refactoring was also done for node editor properties

**Comment by kskenyon** [comment]
Thanks. Works great.
