### ISSUE TITLE
This node stopped working for me

### ISSUE THREAD

**Issue by k5map** [dre2901/node-red-contrib-myq#9]
I've been using this node for years but a few days ago it stopped reporting device status.

When I attempt to retrieve the device status, I get multiple errors:

Error received
Could not refresh devices!

I've confirmed my account information is correct so asking those who use this node if there's a MyQ cloud issue or is it just me?

**Comment by AaronStephens** [comment]
I just checked mine, and it's responding to status requests as expected.

**Comment by k5map** [comment]
I resolved my issue... it was with the payload value for the inject node (it was not blank or info)
